export const CREATE_SHIPMENT = 'CREATE_SHIPMENT';
export const UPDATE_SHIPMENT = 'UPDATE_SHIPMENT';
export const DELETE_SHIPMENT = 'DELETE_SHIPMENT';
export const FIND_SHIPMENT = 'FIND_SHIPMENT';
export const FETCH_SHIPMENT = 'FETCH_SHIPMENT';
export const FILTER_SHIPMENT = 'FILTER_SHIPMENT';